defaults:
  - _self_
  - task@_global_: cheetah_run

# environment settings
num_eval_videos: 30
dynamic_background: true
# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
snapshot_interval: 10000
resume_from_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: true
use_wandb: true
wandb_resume_run_id: none  # set to enable resuming W&B run when resuming from snapshot
# agent
lr: 1e-4
feature_dim: 50
# directories
root_dir: pse/results/${task_name}/${experiment}

agent:
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_wandb: ${use_wandb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
