defaults:
  - _self_
  - task@_global_: ball_in_cup_catch

# environment settings
num_eval_videos: 30
train_background_videos: ['bear']  # either 'training' or a list of valid video names from DAVIS17_TRAINING_VIDEOS
num_train_videos: 1  # only used if train_background_videos is set to 'training'
dynamic_background: true
# task settings
frame_stack: 4
action_repeat: 3
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
snapshot_interval: 10000
resume_from_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: true
use_tb: false
use_wandb: true
# experiment
experiment: debug_baseline_experiment
# agent
lr: 1e-4
feature_dim: 50
# directories
root_dir: pse/results/${experiment}/${task_name}

agent:
  _target_: pse.agents.drq.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  use_wandb: ${use_wandb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
