max_episode_len: 1000
task_name: ball_in_cup_catch
total_episodes: 500
episodes_per_seed: 10
snapshot_dir: /home/kit/anthropomatik/ht9329/pse/results/${task_name}/optimal_policy/snapshots
metric_data_dir: /home/kit/anthropomatik/ht9329/pse/results/${task_name}/metric_data
action_repeat: 2
frame_stack: 3
discount: 0.99