defaults:
  - base_config
  - _self_

num_seed_frames: 4
num_train_frames: 8
save_snapshot: false
batch_size: 2
device: cpu
use_wandb: false
experiment: test_pse
root_dir: pse/debug_results/${experiment}